apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce      # only one pod can read/write at a time
  resources:
    requests:
      storage: 5Gi       # 5 gigabytes of storage
