apiVersion: v1
kind: ConfigMap
metadata:
  name: order-db-init
data:
  01-create-orders.sql: |
    CREATE SCHEMA IF NOT EXISTS orders;

    CREATE TABLE IF NOT EXISTS orders.orders (
        id SERIAL PRIMARY KEY,
        product JSONB NOT NULL,
        status VARCHAR(50) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-db-config
data:
  DB_HOST: "order-db"
  DB_NAME: "orders_user"
  DB_USER: "orders_user"
