apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.auth.secretKey | quote }}
  ADMIN_USER: {{ .Values.auth.adminUser | quote }}
  ADMIN_PASS: {{ .Values.auth.adminPass | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
type: Opaque
stringData:
  DB_HOST: {{ .Values.orderDb.host | quote }}
  DB_NAME: {{ .Values.orderDb.name | quote }}
  DB_USER: {{ .Values.orderDb.user | quote }}
  DB_PASS: {{ .Values.orderDb.pass | quote }}
